### PR TITLE
View All Users

### LINKED ISSUE #23: View All User Profiles
As an admin, I would like to see a list of all the User Profiles so that I can keep track of who is using the system.

**Given** the user is an admin in the Tabloid application  
**When** they select the `User Profiles` menu option  
**Then** they should be directed to the User Profiles list page  
**And** each user in the list should display the full name, the display name and the user type.
**And** the list should be in ordered alphabetically by user display name

### LINKED ISSUE #24: View User Profile Details
As an admin, I would like to see the content of a User Profile so I can read it.

**Given** a user is viewing a list of User Profiles  
**When** they select a user
**Then** they should be directed to a User Profile Detail page

User Profile Details include:

* Full name
* Avatar image (if exists, else use a default image)
* Display name
* Email
* Creation Date (MM/DD/YYYY)
* User Profile type

### LINKED ISSUE #25: Deactivate a User Profile
As an admin I would like the ability to deactivate a User Profile so that I can prevent unsavory characters from using the system.

**Given** an admin is vising the list of User Profiles  
**When** they select the `Deactivate` option  
**Then** they should be prompted to confirm deactivation  

**Given** the admin wishes to confirm the deactivation    
**When** they the select the option to confirm  
**Then** the User Profile should be deactivated in the system  
**And** the admin should be directed back to the User Profile list  

**Given** the admin decides not to confirm the deactivation    
**When** they the select the option to reject confirmation  
**Then** the User Profile should NOT be deactivated  
**And** the admin should be directed back to the User Profile list  

**Given** a user is deactivated  
**When** they try to login to the system  
**Then** the system should behave as if the user does not exist

### LINKED ISSUE #26: Reactivate a User Profile
As an admin I would like the ability to reactivate a User Profile so that I can correct an mistaken User Profile deactivation

**Given** an admin is vising the list of User Profiles  
**When** they select the `View Deactivated` option  
**Then** they should see a list of deactivated User Profiles

**Given** an admin sees a User Profile they wish to reactivate  
**When** they select the `Reactivate` option  
**Then** the user should be reactivated  
**And** the user should have the same access to the system they had prior to being deactivated

### LINKED ISSUE #58: Hide Posts from Deactivated Users
When a user is deactivated, their posts should not appear in the Post List

### PR DESCRIPTION
**Pull request by iparkerhodge**
### Changes
1. Created getAllUsers method in API repository and corresponding HttpGet route in controller
2. Hid users tab in header from Author user types
3. Created User Details view
4. Enabled User Deactivation
5. Added list of deactivated users to users list
6. Enable Reactivate User feature

### To Test
1. Run the SQL script 
`ALTER TABLE UserProfile
ADD IsApproved BIT DEFAULT 1 NOT NULL`
2. Login as an admin and view the users list
3. Login as an author ensure you cannot see the users tab in the header
4. Ensure you cannot navigate to the users list by the URL as an author `http://localhost:3000/users`
5. Try deactivating a user and ensure they no longer appear in the active users list, they do appear in the deactivated users list, and their posts no longer appear in the post list
6. Ensure you can see the deactivated users when you click the show deactivated button
7. Ensure you cannot login as a deactivated user

***NOTE: I turned off the 'launch browser' setting in the API bc I hate it.***

### CODE REVIEW

**Review by heidijane — CHANGES_REQUESTED** [review]
There is one minor error when I go to the Users page:
`Warning: validateDOMNesting(...): <h3> cannot appear as a child of <thead>`

Other than that, everything works perfectly!

**Review by heidijane — APPROVED** [review]

**Review by kristen-howton — CHANGES_REQUESTED** [review]
I love the way the way it looks, I like the styling of the deactivated users
- Ticket 23, please have nav bar say "user profiles"
- Ticket 24, please have the user profile details also include a default avatar image, creation date, and userprofile type
- Ticket 25, please make it where I have to confirm to deactivate a user. 
- Ticket 25, while I love the pop up window that tells the user they have been deactivated, but the ticket says "the system should behave as if the user does not exist"
- If I attempt to deactivate myself, then I get an unhanded exception error

You can search for deactivated users posts in nav bar, I don't think this is a huge deal, though.

**Comment by iparkerhodge** [comment]
### Changes
- Changed Users to User Profiles in header
- Created default user profile image
- Created confirmation modal for user deactivation
- Users get an alert before deactivate themselves
- A deactivated user cannot register an account with that email
- An alert is displayed when a user tries to register an account with an existing email
### Steps To Test
1. Check that a user with no profile image as the default profile image
2. Check the confirm deactivate modal
3. Try deactivating yourself. Then try logging in with that user. Then try registering with that user.

**Review by heidijane — CHANGES_REQUESTED** [review]
Looks great! Everything works, there are just a couple things I noticed.
- The account create date on the user profile is unformatted, I think it is supposed to be in MM/DD/YYYY
- When a user registers a new account they are set as deactivated by default, not sure if this is intended?

**Review by heidijane — APPROVED** [review]

**Review by kristen-howton — APPROVED** [review]
:shipit: 
Perfect!!

**Review by kristen-howton — APPROVED** [review]
Thank you for making the changes, it works perfectly now!
:shipit:

**Pull request merged**
