### PR TITLE
Category CRUD

### LINKED ISSUE #10: Create a Category
As an admin I would like to be able to create a new category so that I can give authors the ability to better classify their posts.

**Given** an admin is on the Category list page  
**When** they select the `Create Category` button  
**Then** they should be directed to a form in which they can enter a new category name  

**Given** an admin has entered a Category name  
**When** they click the `Save` button  
**Then** a new category should be saved to the database  
**And** the admin should be directed to the Category list page

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

### LINKED ISSUE #11: Delete a Category
As an admin I would like to be able to delete a Category so that I can remove any that are not needed.

**Given** an admin is vising the list of Categories  
**When** they select the `Delete` option  
**Then** they should be prompted to confirm the deletion  

**Given** the admin wishes to confirm the delete  
**When** they the select the option to confirm  
**Then** the Category should be removed from the system  
**And** the admin should be directed back to the Category list  

**Given** the admin decides not to confirm the delete  
**When** they the select the option to reject confirmation  
**Then** the Category should NOT be removed from the system  
**And** the admin should be directed back to the Category list  

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

### LINKED ISSUE #12: Edit a Category
As an admin I would like to be able to modify a Category so that I can rephrase the name if I think of something more appropriate.

**Given** the user is viewing the Category list  
**When** they select the option to edit an Category  
**Then** the user should be directed to a form and given the ability to change the Category's name  

**Given** the user is finished updating the Category information  
**When** they click the `Save` button  
**Then** the updated Category should be saved to the database  
**And** the user should be redirected to the new Category List page  

**Given** the user has decided not to edit the Category  
**When** they click the `Cancel` button  
**Then** the user should be redirected back to the list page

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

### LINKED ISSUE #48: Add Category Dropdown To Post Form
Add a <select> dropdown to the post form to allow the user to select a category for the post, **after the category repository has been created**

### PR DESCRIPTION
**Pull request by ygitore**
Created Add, Edit and Delete category client and server side CRUD functionality
#### How to test
1. Click on Add new Category button then modal pop up add category name then click on save category button
you will see category added to list of category
2. When the Delete option selected then modal popup to confirm the deletion. when delete button is clicked category will be deleted from database.
3. When select the option to edit an Category
Then the page will be directed to a form and given the ability to change the Category's name. When save changes button is clicked then page will be redirected to new list of category

### CODE REVIEW

**Review by heidijane — APPROVED** [review]
👍 Everything appears to be working

**Review by iparkerhodge — CHANGES_REQUESTED** [review]
### Changes
1. When a category is deleted, all of the posts that have that category need to now have the category "Unassigned"
2. Unassigned should not be able to be deleted as a category
3. A user should be able to choose 'Unassigned' when creating a post

**Review by kristen-howton — APPROVED** [review]
:shipit:

**Review by heidijane — CHANGES_REQUESTED** [review]
There are a couple things in the code that need to be cleaned up but otherwise everything works. Line 16 of CategoryList.js needs a modification. Instead of `Key = {category.id}` it should be `key={category.id}`. The extra console.logs should be removed as well.

**Review by heidijane — APPROVED** [review]

**Pull request merged**
