### PR TITLE
Create, Edit, Delete Posts

### LINKED ISSUE #6: Create a Post
As an author, I would like to be able to create Posts so I can share my thoughts with the world.

**Given** a user is in the app  
**When** they select the `New Post` menu option
**Then** they should be directed to a page with a form for creating a new post

**Given** the user has entered the relevant information for a Post
**When** they click the `Save` button  
**Then** the Post should be saved to the database  
**And** the creation datetime should be automatically set to the current date and time  
**And** the post should automatically be approved  
**And** the user should be recorded as the author of the Post  
**And** the user should be redirected to the new Post's details page

The "relevant information" for a Post is

* Title
* Content
* Category
* Header Image URL (optional)
* Publication Date (optional)

### LINKED ISSUE #7: Delete a Post
As an author I would like the ability to remove a post I have written so that I can prevent others from reading it when I decide it is no longer something I wish people to read.

**Given** an author is viewing a Post that they have written  
**When** they select the delete option  
**Then** they should be presented to confirm the deletion    

**Given** the author wishes to confirm the delete  
**When** they the select the option to confirm  
**Then** the Post should be removed from the system  
**And** the author should be directed back to the Post list  

**Given** the author decides not to confirm the delete  
**When** they the select the option to reject confirmation  
**Then** the Post should NOT be removed from the system  
**And** the author should be directed back to the Post details

### LINKED ISSUE #8: Edit a Post
As a author I would like to be able to modify my Posts so that I can correct mistakes or add additional content.

**Given** the user is viewing the Post list  
**When** they select the option to edit an Post  
**Then** the user should be directed to a form and given the ability to change the Post's information  

**Given** the user is finished updating the Post information  
**When** they click the `Save` button  
**Then** the updated Post should be saved to the database  
**And** the user should be redirected to the new Post's details page

**Given** the user has decided not to edit the Post  
**When** they click the `Cancel` button  
**Then** the user should be redirected back to the list page

Editable Information

* Title
* Content
* Category
* Header Image URL (optional)
* Publication Date (optional)

### PR DESCRIPTION
**Pull request by iparkerhodge**
### Changes
1. Created Add Post Form and related functions
2. Created Edit Post Form and related functions
3. Created Delete post button that initiates a confirmation modal and deletes upon user confirmation

### To Test
1. Create a post. Try leaving the publish date blank. (NOTE: for now all categoryIds for added posts are 1, until we can implement a select dropdown using the category repo/provider)
2. Delete a post written by your current user
3. Try editing a post written by the current user.
4. Ensure all the modals work properly.
5. Ensure merge conflicts were resolved correctly and Tags components are still functional

### CODE REVIEW

**Review by heidijane — APPROVED** [review]
There was one merge conflict that still was appeared when I opened the branch. In Header.js the links for New Post and Tag Management were trying to go on the same line, but after fixing that everything works perfectly! I'm going to go ahead and approve. 👍

**Comment by iparkerhodge** [comment]
fixed the merge conflict and pushed it!

**Review by ygitore — COMMENTED** [review]
**Microsoft.EntityFrameworkCore.DbUpdateException:** 'An error occurred while updating the entries. See the inner exception for details.
**inner exception**
Microsoft.EntityFrameworkCore.DbUpdateException: 'An error occurred while updating the entries. See the inner exception for details.'

**Review by ygitore — APPROVED** [review]
👍 Great!!

**Review by kristen-howton — APPROVED** [review]
:shipit:

**Pull request merged**
